# Generated by Django 6.0.7 on 2026-08-02 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_updated_09e193_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_msg_conv_created_idx',
            old_name='chat_messag_convers_3154fc_idx',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='chat_conv_upd_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='chat_msg_conv_read_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), ('image__isnull', True), _negated=True), name='chat_message_has_content_or_image'),
        ),
    ]
