# Generated by Django 6.0.7 on 2026-08-02 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_conversation_chat_conver_updated_09e193_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='chat_message_has_content_or_image',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('content__gt', ''), ('image__gt', ''), _connector='OR'), name='chat_message_has_content_or_image'),
        ),
    ]
