# Generated by Django 6.0.7 on 2026-08-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pair_key',
            field=models.CharField(default=None, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
