# Generated by Django 6.0.7 on 2026-08-03 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_backfill_conversation_pair_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='muted_by',
            field=models.ManyToManyField(blank=True, related_name='muted_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
