# Generated by Django 6.0.7 on 2026-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blocked_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
