# Generated by Django 6.0.7

from django.db import migrations


def backfill_display_name(apps, schema_editor):
    """Copy the signup "full name" into display_name for accounts created
    before the signup form stored it there (it used first_name instead), so
    their real name shows up in conversation headers and Settings."""
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(display_name="", first_name__gt=""):
        user.display_name = user.first_name
        user.save(update_fields=["display_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_theme"),
    ]

    operations = [
        migrations.RunPython(backfill_display_name, migrations.RunPython.noop),
    ]
