# Generated by Django 6.0.7 on 2026-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'My Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='read_receipts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
    ]
